### ISSUE TITLE
Hadith number error

### ISSUE THREAD

**Issue by muhammed-abuodeh** [ShathaTm/LK-Hadith-Corpus#1]
First of all thank you for this valuable resource!

Second, there is a minor error in the hadith number sequence in chapter 4 of AlBukhari [here](https://github.com/ShathaTm/LK-Hadith-Corpus/blob/master/Bukhari/Chapter4.csv#L89). It seems that in line 89 the numbering is off, affecting the subsequent hadith numbers within chapter 4. The hadith numbers go in the following order:
219
220
221
**220**
222

It does not seem to affect chapter 5.

**Comment by ShathaTm** [comment]
@[muhammed-abuodeh](https://github.com/muhammed-abuodeh)

Thank you so much for your feedback.

I must say that Albukhari was manually checked against the source (https://waqfeya.net/book.php?bid=3584). In the book, the numbering of some Hadiths is compound, for example, you will find a hadith with the number  410-411 ( instead of just 410), then the hadith following is numbered 412.

So you have the option to take the numbering as is in the book, or you can extract the data then automatically number the hadiths.  

Cheers!
